version: '3'
services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-21-aug-2022/motion-backend-groups/team-4/team4motion:latest
    env_file:
      - ./envs/prod.env
    command: "sh /scripts/prod.sh"
    volumes:
      - static_files:/static-files
      - media_files:/media-files
      - build:/frontend/build
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres_db:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - static_files:/static-files
      - media_files:/media-files
      - /etc/letsencrypt:/etc/letsencrypt
      - build:/build


volumes:
  postgres_db:
  static_files:
  media_files:
  build:
